language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install coverage
script: python tests/svn_wrapper_tests.py
after_success: coverage report
branches:
  only:
    - SVN_basic